[package]
name = "inventory_system_app"
version = "0.1.0"
edition = "2021"
authors = ["Anatolii Maltsev <https://www.linkedin.com/in/anatolii-maltsev/>"]

[dependencies]
cursive = "0.21.1"
serde = { version = "1.0",features = ["derive"]}
serde_json = "1.0.132"
